version: '3'

services:

  app:
    image: 'springio/gs-spring-boot-docker:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mightygram
      - SPRING_DATASOURCE_USERNAME=mightygram
      - SPRING_DATASOURCE_PASSWORD=mightygram
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_DATASOURCE_INITIALIZATION_MODE=always
      - SPRING_JPA_PROPERTIES_HIBERNATE_LOB_NON_CONTEXTUAL_CREATION=true
    ports:
      - "8080:8080"

  db:
    container_name: db
    image: postgres:13
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - app-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mightygram
      - POSTGRES_USER=mightygram
      - POSTGRES_PASSWORD=mightygram

volumes:
  app-db:
    driver: local

