version: '2'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=mightygram
      - POSTGRES_PASSWORD=mightygram
      - POSTGRES_DB=mightygram
    ports:
      - '5432:5432'