version: '3'

services:

   db:
    container_name: db
    image: postgres:13
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - app-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mightygram
      - POSTGRES_USER=mightygram
      - POSTGRES_PASSWORD=mightygram

volumes:
  app-db:
    driver: local

